### ISSUE TITLE
overflowing text

### ISSUE THREAD

**Issue by jansindl3r** [jansindl3r/workshops#4]
![Screenshot 2020-02-25 at 16 15 38](https://user-images.githubusercontent.com/44162266/75260564-18e75900-57ea-11ea-8de4-09c45a39222b.png)

**Comment by loukotal** [comment]
to je issue? :(

**Comment by jansindl3r** [comment]
tak me tam nejde zascrollovat

**Comment by loukotal** [comment]
fixnuto zde https://github.com/jansindl3r/workshops/commit/c9e5aa458adf50c5ab617efd75f87346fa9e85b6
 \+ se da zoomovat
